id: IEE84AE35
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T15:43:04+00:00'
last_modified: '2022-06-10T09:20:05.354856+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4051
  title: ཟབ་ཆོས་ཞི་ཁྲོ་དགོངས་པ་རང་གྲོལ་གྱི་དབུ་ཚལ་དྲི་མའི་འཇིགས་སྐྱོབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F42D:
      image_group_id: I3CN4238
      title: Volume 1 of zab chos zhi khro dgongs pa rang grol gyi dbu tshal dri ma'i
        'jigs skyob/
      total_pages: 1066
      order: 1
      base_file: F42D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
